name: demo
services:
  mysql:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prime
      MYSQL_USER: prime
      MYSQL_PASSWORD: password
    ports:
      - 3306:3307
    command: mysqld --lower_case_table_names=1 --skip-mysqlx --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.4.1
    ports:
      - 6379:6380
    networks:
      - my_network

  backend:
    image: phamduchuy92/test-prime-backend:latest
    ports:
      - 8080:8080
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data: