name: demo
services:
  mysql:
    container_name: mysql
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prime
      MYSQL_USER: prime
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    command: mysqld --lower_case_table_names=1 --skip-mysqlx --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:7.4.1
    ports:
      - 6380:6379
    networks:
      - my_network

  backend:
    container_name: backend
    image: phamduchuy92/test-prime-backend:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/prime
      SPRING_DATASOURCE_USERNAME: prime
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - my_network

  frontend:
    container_name: frontend
    image: phamduchuy92/test-prime-frontend:latest
    ports:
      - 4433:4433
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data: